<?php

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @extends AbstractType<string|null>
 */
class FontawesomeType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver): void
    {
        $choices = self::getIcons();
        $choiceAttr = [];

        foreach ($choices as $label => $value) {
            $choiceAttr[$label] = ['data-icon' => $value];
        }

        $resolver->setDefaults([
            'choices' => $choices,
            'choice_attr' => $choiceAttr,
        ]);
    }

    public function getParent(): string
    {
        return ChoiceType::class;
    }

    /**
     * @return array<string, non-empty-string>
     */
    public static function getIcons(): array
    {
        return [
            'Maison' => 'fa-solid fa-house',
            'Maison Cheminee' => 'fa-solid fa-house-chimney',
            'Fleche Haut' => 'fa-solid fa-arrow-up',
            'Fleche Bas' => 'fa-solid fa-arrow-down',
            'Fleche Gauche' => 'fa-solid fa-arrow-left',
            'Fleche Droite' => 'fa-solid fa-arrow-right',
            'Chevron Haut' => 'fa-solid fa-chevron-up',
            'Chevron Bas' => 'fa-solid fa-chevron-down',
            'Chevron Gauche' => 'fa-solid fa-chevron-left',
            'Chevron Droite' => 'fa-solid fa-chevron-right',
            'Barres' => 'fa-solid fa-bars',
            'Grille' => 'fa-solid fa-grip',
            'Points Suspension' => 'fa-solid fa-ellipsis',
            'Points Suspension Vertical' => 'fa-solid fa-ellipsis-vertical',

            'Utilisateur' => 'fa-solid fa-user',
            'Utilisateurs' => 'fa-solid fa-users',
            'Groupe Utilisateurs' => 'fa-solid fa-user-group',
            'Ajouter Utilisateur' => 'fa-solid fa-user-plus',
            'Retirer Utilisateur' => 'fa-solid fa-user-minus',
            'Utilisateur Verifie' => 'fa-solid fa-user-check',
            'Bouclier Utilisateur' => 'fa-solid fa-user-shield',
            'Parametres Utilisateur' => 'fa-solid fa-user-gear',
            'Enveloppe' => 'fa-solid fa-envelope',
            'Enveloppe Ouverte' => 'fa-solid fa-envelope-open',
            'Commentaire' => 'fa-solid fa-comment',
            'Commentaires' => 'fa-solid fa-comments',
            'Commentaire Points' => 'fa-solid fa-comment-dots',
            'Message' => 'fa-solid fa-message',
            'Telephone' => 'fa-solid fa-phone',
            'Telephone Inverse' => 'fa-solid fa-phone-flip',
            'Arobase' => 'fa-solid fa-at',
            'Hashtag' => 'fa-solid fa-hashtag',
            'Lien' => 'fa-solid fa-link',
            'Lien Casse' => 'fa-solid fa-link-slash',
            'Partager' => 'fa-solid fa-share',
            'Trompette' => 'fa-solid fa-bullhorn',
            'Boite Mail' => 'fa-solid fa-inbox',
            'Cloche' => 'fa-solid fa-bell',
            'Cloche Coupee' => 'fa-solid fa-bell-slash',
            'Clips' => 'fa-solid fa-paperclip',
            'Antenne' => 'fa-solid fa-tower-broadcast',
            'Wifi' => 'fa-solid fa-wifi',
            'Bluetooth' => 'fa-brands fa-bluetooth-b',
            'Balise' => 'fa-solid fa-tower-cell',
            'Flux RSS' => 'fa-solid fa-rss',

            'Stylo' => 'fa-solid fa-pen',
            'Crayon' => 'fa-solid fa-pencil',
            'Stylo Plume' => 'fa-solid fa-pen-fancy',
            'Plume' => 'fa-solid fa-pen-nib',
            'Editer' => 'fa-solid fa-pen-to-square',
            'Plus' => 'fa-solid fa-plus',
            'Moins' => 'fa-solid fa-minus',
            'Cocher' => 'fa-solid fa-check',
            'Double Coche' => 'fa-solid fa-check-double',
            'Cercle Coche' => 'fa-solid fa-circle-check',
            'Cercle Croix' => 'fa-solid fa-circle-xmark',
            'Cercle Plus' => 'fa-solid fa-circle-plus',
            'Cercle Moins' => 'fa-solid fa-circle-minus',
            'Poubelle' => 'fa-solid fa-trash',
            'Poubelle Aluminium' => 'fa-solid fa-trash-can',
            'Annuler' => 'fa-solid fa-xmark',
            'Copier' => 'fa-solid fa-copy',
            'Couper' => 'fa-solid fa-scissors',
            'Rogner' => 'fa-solid fa-crop',
            'Baguette Magique' => 'fa-solid fa-wand-magic',
            'Curseurs' => 'fa-solid fa-sliders',
            'Filtre' => 'fa-solid fa-filter',
            'Gomme' => 'fa-solid fa-eraser',
            'Surligneur' => 'fa-solid fa-highlighter',
            'Tampon' => 'fa-solid fa-stamp',
            'Signature' => 'fa-solid fa-signature',
            'Palette' => 'fa-solid fa-palette',
            'Pinceau' => 'fa-solid fa-paintbrush',
            'Roller' => 'fa-solid fa-paint-roller',
            'Marqueur' => 'fa-solid fa-marker',
            'Oeil' => 'fa-solid fa-eye',
            'Oeil Cache' => 'fa-solid fa-eye-slash',
            'Clone' => 'fa-solid fa-clone',
            'Engrenage' => 'fa-solid fa-gear',
            'Engrenages' => 'fa-solid fa-gears',

            'Fichier' => 'fa-solid fa-file',
            'Fichier Texte' => 'fa-solid fa-file-lines',
            'Fichier Image' => 'fa-solid fa-file-image',
            'Fichier Audio' => 'fa-solid fa-file-audio',
            'Fichier Video' => 'fa-solid fa-file-video',
            'Fichier Code' => 'fa-solid fa-file-code',
            'Fichier PDF' => 'fa-solid fa-file-pdf',
            'Fichier Word' => 'fa-solid fa-file-word',
            'Fichier Excel' => 'fa-solid fa-file-excel',
            'Fichier CSV' => 'fa-solid fa-file-csv',
            'Fichier ZIP' => 'fa-solid fa-file-zipper',
            'Fichier Importer' => 'fa-solid fa-file-import',
            'Fichier Exporter' => 'fa-solid fa-file-export',
            'Dossier' => 'fa-solid fa-folder',
            'Dossier Ouvert' => 'fa-solid fa-folder-open',
            'Dossier Ajouter' => 'fa-solid fa-folder-plus',
            'Dossier Retirer' => 'fa-solid fa-folder-minus',
            'Archive' => 'fa-solid fa-box-archive',
            'Disquette' => 'fa-solid fa-floppy-disk',
            'Note Adhesive' => 'fa-solid fa-note-sticky',
            'Coller' => 'fa-solid fa-paste',
            'Image' => 'fa-solid fa-image',
            'Images' => 'fa-solid fa-images',
            'Telecharger' => 'fa-solid fa-download',
            'Envoyer' => 'fa-solid fa-upload',
            'Nuage' => 'fa-solid fa-cloud',
            'Nuage Telecharger' => 'fa-solid fa-cloud-arrow-down',
            'Nuage Envoyer' => 'fa-solid fa-cloud-arrow-up',

            'Barre Horizontale' => 'fa-solid fa-chart-bar',
            'Courbe' => 'fa-solid fa-chart-line',
            'Camembert' => 'fa-solid fa-chart-pie',
            'Barres Simples' => 'fa-solid fa-chart-simple',
            'Diagramme' => 'fa-solid fa-diagram-project',
            'Tableau' => 'fa-solid fa-table',
            'Colonnes Tableau' => 'fa-solid fa-table-columns',
            'Liste Cochee' => 'fa-solid fa-list-check',
            'Pourcentage' => 'fa-solid fa-percent',
            'Calculatrice' => 'fa-solid fa-calculator',

            'Base de Donnees' => 'fa-solid fa-database',
            'Serveur' => 'fa-solid fa-server',
            'Disque Dur' => 'fa-solid fa-hard-drive',
            'Ordinateur' => 'fa-solid fa-laptop',
            'Bureau' => 'fa-solid fa-desktop',
            'Tablette' => 'fa-solid fa-tablet',
            'Clavier' => 'fa-solid fa-keyboard',
            'Impression' => 'fa-solid fa-print',
            'Camera' => 'fa-solid fa-camera',
            'Micro' => 'fa-solid fa-microphone',
            'Micro Lignes' => 'fa-solid fa-microphone-lines',
            'Satellite' => 'fa-solid fa-satellite',
            'Antenne Parabole' => 'fa-solid fa-satellite-dish',
            'Carte SD' => 'fa-solid fa-sd-card',
            'Carte SIM' => 'fa-solid fa-sim-card',
            'Memoire' => 'fa-solid fa-memory',
            'Microchip' => 'fa-solid fa-microchip',
            'Manette' => 'fa-solid fa-gamepad',
            'Cartouche' => 'fa-solid fa-plug',
            'Tele' => 'fa-solid fa-tv',
            'Affichage' => 'fa-solid fa-display',
            'Ecran' => 'fa-solid fa-computer',
            'Souris' => 'fa-solid fa-computer-mouse',
            'Onduleur' => 'fa-solid fa-tachograph-digital',
            'Tableau de Bord' => 'fa-solid fa-gauge-high',
            'Ecran Portable' => 'fa-solid fa-house-laptop',
            'Reseau' => 'fa-solid fa-network-wired',
            'Cle USB' => 'fa-solid fa-usb',
            'Brancher' => 'fa-solid fa-plug',
            'Couper le courant' => 'fa-solid fa-power-off',
            'Telecommande' => 'fa-solid fa-walkie-talkie',

            'Cadenas' => 'fa-solid fa-lock',
            'Cadenas Ouvert' => 'fa-solid fa-lock-open',
            'Bouclier' => 'fa-solid fa-shield',
            'Bouclier Helve' => 'fa-solid fa-shield-halved',
            'Bouclier Verifie' => 'fa-solid fa-shield-check',
            'Cle' => 'fa-solid fa-key',
            'Empreinte Digitale' => 'fa-solid fa-fingerprint',
            'Carte Identite' => 'fa-solid fa-id-card',
            'Badge' => 'fa-solid fa-id-badge',
            'Marteau' => 'fa-solid fa-gavel',
            'Balance' => 'fa-solid fa-scale-balanced',
            'Interdit' => 'fa-solid fa-ban',
            'Avertissement' => 'fa-solid fa-triangle-exclamation',
            'Exclamation' => 'fa-solid fa-circle-exclamation',
            'Information' => 'fa-solid fa-circle-info',
            'Question' => 'fa-solid fa-circle-question',
            'Crane' => 'fa-solid fa-skull',
            'Crane Trefles' => 'fa-solid fa-skull-crossbones',
            'Bombe' => 'fa-solid fa-bomb',
            'Feu' => 'fa-solid fa-fire',
            'Flamme' => 'fa-solid fa-fire-flame-curved',
            'Sourd' => 'fa-solid fa-ear-deaf',
            'Ecouter' => 'fa-solid fa-ear-listen',

            'Edifice' => 'fa-solid fa-building',
            'Institutions' => 'fa-solid fa-building-columns',
            'Colisee' => 'fa-solid fa-landmark',
            'Eglise' => 'fa-solid fa-church',
            'Ville' => 'fa-solid fa-city',
            'Entrepot' => 'fa-solid fa-warehouse',
            'Usine' => 'fa-solid fa-industry',
            'Magasin' => 'fa-solid fa-shop',
            'Hotel' => 'fa-solid fa-hotel',
            'Hopital' => 'fa-solid fa-hospital',
            'Ecole' => 'fa-solid fa-school',
            'Dome' => 'fa-solid fa-landmark-dome',
            'Drapeau' => 'fa-solid fa-landmark-flag',
            'Tente' => 'fa-solid fa-tent',
            'Tentes' => 'fa-solid fa-tents',

            'Fleche Haut Longue' => 'fa-solid fa-arrow-up-long',
            'Fleche Bas Longue' => 'fa-solid fa-arrow-down-long',
            'Fleche Gauche Longue' => 'fa-solid fa-arrow-left-long',
            'Fleche Droite Longue' => 'fa-solid fa-arrow-right-long',
            'Pointer' => 'fa-solid fa-arrow-pointer',
            'Rotation Gauche' => 'fa-solid fa-arrow-rotate-left',
            'Rotation Droite' => 'fa-solid fa-arrow-rotate-right',
            'Rotations' => 'fa-solid fa-arrows-rotate',
            'Melanger' => 'fa-solid fa-shuffle',
            'Retourner' => 'fa-solid fa-reply',
            'Repondre Tous' => 'fa-solid fa-reply-all',
            'Partager Carre' => 'fa-solid fa-share-from-square',
            'Trier' => 'fa-solid fa-sort',
            'Trier Bas' => 'fa-solid fa-sort-down',
            'Trier Haut' => 'fa-solid fa-sort-up',
            'Gauche Droite' => 'fa-solid fa-left-right',
            'Haut Bas' => 'fa-solid fa-up-down',
            'Maximiser' => 'fa-solid fa-maximize',
            'Minimiser' => 'fa-solid fa-minimize',
            'Recycler' => 'fa-solid fa-recycle',
            'Avancer' => 'fa-solid fa-forward',
            'Reculer' => 'fa-solid fa-backward',
            'Play' => 'fa-solid fa-play',
            'Pause' => 'fa-solid fa-pause',
            'Stop' => 'fa-solid fa-stop',
            'Ejecter' => 'fa-solid fa-eject',
            'Volume Haut' => 'fa-solid fa-volume-high',
            'Volume Bas' => 'fa-solid fa-volume-low',
            'Volume Couper' => 'fa-solid fa-volume-xmark',
            'Avancer Rapide' => 'fa-solid fa-forward-fast',
            'Reculer Rapide' => 'fa-solid fa-backward-fast',
            'Suivant' => 'fa-solid fa-forward-step',
            'Precedent' => 'fa-solid fa-backward-step',

            'Carte' => 'fa-solid fa-map',
            'Point Carte' => 'fa-solid fa-map-pin',
            'Localisation' => 'fa-solid fa-location-pin',
            'Localisation Point' => 'fa-solid fa-location-dot',
            'Loupe' => 'fa-solid fa-magnifying-glass',
            'Loupe Plus' => 'fa-solid fa-magnifying-glass-plus',
            'Loupe Moins' => 'fa-solid fa-magnifying-glass-minus',
            'Boussole' => 'fa-solid fa-compass',
            'Route' => 'fa-solid fa-route',
            'Bicyclette' => 'fa-solid fa-bicycle',
            'Voiture' => 'fa-solid fa-car',
            'Bus' => 'fa-solid fa-bus',
            'Camion' => 'fa-solid fa-truck',
            'Avion' => 'fa-solid fa-plane',
            'Train' => 'fa-solid fa-train',
            'Metro' => 'fa-solid fa-train-subway',
            'Bateau' => 'fa-solid fa-ship',
            'Fusee' => 'fa-solid fa-rocket',
            'Taxi' => 'fa-solid fa-taxi',
            'Moto' => 'fa-solid fa-motorcycle',
            'Feu rouge' => 'fa-solid fa-traffic-light',
            'Croisement' => 'fa-solid fa-diamond-turn-right',

            'Argent' => 'fa-solid fa-money-bill',
            'Facture' => 'fa-solid fa-file-invoice',
            'Portefeuille' => 'fa-solid fa-wallet',
            'Coffre-Fort' => 'fa-solid fa-vault',
            'Tresor' => 'fa-solid fa-sack-dollar',
            'Piggy Bank' => 'fa-solid fa-piggy-bank',
            'Piece' => 'fa-solid fa-coins',
            'Carte Bancaire' => 'fa-solid fa-credit-card',
            'Inventaire' => 'fa-solid fa-cash-register',
            'Euro' => 'fa-solid fa-euro-sign',
            'Dollar' => 'fa-solid fa-dollar-sign',
            'Livre' => 'fa-solid fa-book',
            'Cahier' => 'fa-solid fa-book-open',
            'Calendrier' => 'fa-solid fa-calendar',
            'Calendrier Jours' => 'fa-solid fa-calendar-days',
            'Horloge' => 'fa-solid fa-clock',
            'Sablier' => 'fa-solid fa-hourglass',
            'Liste' => 'fa-solid fa-list',
            'Liste Puces' => 'fa-solid fa-list-ul',
            'Liste Numbers' => 'fa-solid fa-list-ol',
            'Cible' => 'fa-solid fa-bullseye',
            'Certificat' => 'fa-solid fa-certificate',
            'Etiquette' => 'fa-solid fa-tag',
            'Etiquettes' => 'fa-solid fa-tags',
            'Trophee' => 'fa-solid fa-trophy',
            'Etoile' => 'fa-solid fa-star',
            'Coeur' => 'fa-solid fa-heart',
            'Coeur Casse' => 'fa-solid fa-heart-crack',
            'Pouls' => 'fa-solid fa-heart-pulse',

            'Soleil' => 'fa-solid fa-sun',
            'Lune' => 'fa-solid fa-moon',
            'Pluie' => 'fa-solid fa-cloud-rain',
            'Neige' => 'fa-solid fa-snowflake',
            'Vent' => 'fa-solid fa-wind',
            'Eclair' => 'fa-solid fa-bolt',
            'Orage' => 'fa-solid fa-cloud-bolt',
            'Arc-en-ciel' => 'fa-solid fa-rainbow',
            'Nuage Lune' => 'fa-solid fa-cloud-moon',
            'Nuage Soleil' => 'fa-solid fa-cloud-sun',
            'Feuille' => 'fa-solid fa-leaf',
            'Arbre' => 'fa-solid fa-tree',
            'Fleur' => 'fa-solid fa-seedling',
            'Rocher' => 'fa-solid fa-mountain',
            'Montagne' => 'fa-solid fa-mountain-sun',
            'Plage' => 'fa-solid fa-umbrella-beach',
            'Goutte' => 'fa-solid fa-droplet',
            'Goutte Coupee' => 'fa-solid fa-droplet-slash',
            'Eau' => 'fa-solid fa-water',
            'Voilier' => 'fa-solid fa-sailboat',
            'Tornade' => 'fa-solid fa-tornado',
            'Volcan' => 'fa-solid fa-volcano',
            'Astro' => 'fa-solid fa-shuttle-space',
            'Lunette' => 'fa-solid fa-binoculars',
            'Globe' => 'fa-solid fa-globe',

            'Chien' => 'fa-solid fa-dog',
            'Chat' => 'fa-solid fa-cat',
            'Oiseau' => 'fa-solid fa-dove',
            'Dragon' => 'fa-solid fa-dragon',
            'Cheval' => 'fa-solid fa-horse',
            'Grenouille' => 'fa-solid fa-frog',
            'Poisson' => 'fa-solid fa-fish',
            'Araignee' => 'fa-solid fa-spider',
            'Moustique' => 'fa-solid fa-mosquito',
            'Loutre' => 'fa-solid fa-otter',
            'Vermi' => 'fa-solid fa-worm',
            'Pattes' => 'fa-solid fa-paw',
            'Crevette' => 'fa-solid fa-shrimp',

            'Cerveau' => 'fa-solid fa-brain',
            'Os' => 'fa-solid fa-bone',
            'Poumons' => 'fa-solid fa-lungs',
            'Dents' => 'fa-solid fa-teeth',
            'Dents Ouvertes' => 'fa-solid fa-teeth-open',
            'Main' => 'fa-solid fa-hand',
            'Pouce Haut' => 'fa-solid fa-thumbs-up',
            'Pouce Bas' => 'fa-solid fa-thumbs-down',
            'Pied' => 'fa-solid fa-shoe-prints',
            'Silhouette' => 'fa-solid fa-person',
            'Silhouette Marche' => 'fa-solid fa-person-walking',
            'Silhouette Courir' => 'fa-solid fa-person-running',
            'Silhouette Natation' => 'fa-solid fa-person-swimming',
            'Silhouette Velo' => 'fa-solid fa-person-biking',

            'Stethoscope' => 'fa-solid fa-stethoscope',
            'Seringue' => 'fa-solid fa-syringe',
            'Pilules' => 'fa-solid fa-pills',
            'Thermometre' => 'fa-solid fa-thermometer',
            'Bandeau' => 'fa-solid fa-bandage',
            'Trousse' => 'fa-solid fa-kit-medical',
            'Pousse-medic' => 'fa-solid fa-truck-medical',
            'Sang' => 'fa-solid fa-droplet',
            'Virus' => 'fa-solid fa-virus',
            'ADN' => 'fa-solid fa-dna',
            'Microscope' => 'fa-solid fa-microscope',
            'Tasse Prescri' => 'fa-solid fa-prescription-bottle',
            'Coeur Poul' => 'fa-solid fa-heart-pulse',
            'Maladie' => 'fa-solid fa-disease',
            'Radiation' => 'fa-solid fa-radiation',
            'Biohazard' => 'fa-solid fa-biohazard',

            'Pomme' => 'fa-solid fa-apple-whole',
            'Legume' => 'fa-solid fa-carrot',
            'Pizza' => 'fa-solid fa-pizza-slice',
            'Hamburger' => 'fa-solid fa-burger',
            'Glace' => 'fa-solid fa-ice-cream',
            'Bonbons' => 'fa-solid fa-candy-cane',
            'Fromage' => 'fa-solid fa-cheese',
            'Gateau' => 'fa-solid fa-cake-candles',
            'Boeuf' => 'fa-solid fa-drumstick-bite',
            'Oeuf' => 'fa-solid fa-egg',
            'Poivre' => 'fa-solid fa-pepper-hot',
            'Boulangerie' => 'fa-solid fa-bread-slice',
            'Conserve' => 'fa-solid fa-jar',
            'Bouteille' => 'fa-solid fa-wine-bottle',
            'Verre' => 'fa-solid fa-wine-glass',
            'Verre Eau' => 'fa-solid fa-glass-water',
            'Canette' => 'fa-solid fa-beer-mug-empty',
            'Cafe' => 'fa-solid fa-mug-hot',
            'Martini' => 'fa-solid fa-martini-glass-empty',
            'Couverts' => 'fa-solid fa-utensils',
            'Cuillere' => 'fa-solid fa-spoon',
            'Bol Riz' => 'fa-solid fa-bowl-rice',
            'Bol Nourriture' => 'fa-solid fa-bowl-food',
            'Graine' => 'fa-solid fa-seedling',
            'Ble' => 'fa-solid fa-wheat-awn',

            'Echecs' => 'fa-solid fa-chess',
            'Puzzle' => 'fa-solid fa-puzzle-piece',
            'Des' => 'fa-solid fa-dice',
            'Des D20' => 'fa-solid fa-dice-d20',
            'Musique' => 'fa-solid fa-music',
            'Film' => 'fa-solid fa-film',
            'Clap' => 'fa-solid fa-clapperboard',
            'Ticket' => 'fa-solid fa-ticket',
            'Casque' => 'fa-solid fa-headset',
            'Vr' => 'fa-solid fa-vr-cardboard',
        ];
    }
}
